version: 2.1


jobs:
  print-hello:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          command: "echo Hello"
  print-world:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          command: "echo World!"        


workflows:
  welcome-workflow:
    jobs:
      - print-hello
      - print-world:
          requires:
            - print-hello
