version: 2.1


jobs:
  print-hello:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          command: "echo Hello"
  print-my-name:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          command: "echo $MY_NAVID"        


workflows:
  welcome-workflow:
    jobs:
      - print-hello
      - print-my-name:
          requires:
            - print-hello
